import type { LucideIcon } from 'lucide-react'
import {
  Binary,
  Braces,
  CalendarClock,
  Camera,
  CaseSensitive,
  Clock,
  Combine,
  CopyCheck,
  Crop,
  Database,
  Eraser,
  Expand,
  Eye,
  FileBadge,
  FileCode,
  FileDigit,
  FileImage,
  FileOutput,
  Files,
  FileSignature,
  FileStack,
  FileText,
  FileType,
  Fingerprint,
  FolderArchive,
  GitCompare,
  Hash,
  Image,
  ImageDown,
  KeyRound,
  KeySquare,
  Link2,
  ListOrdered,
  Palette,
  PenLine,
  PenTool,
  QrCode,
  Quote,
  Regex,
  RemoveFormatting,
  Repeat,
  Repeat2,
  Scaling,
  ScanText,
  Scissors,
  Shapes,
  Shield,
  ShieldCheck,
  Shrink,
  Sparkles,
  Stamp,
  Table,
  Table2,
  Terminal,
  Workflow,
  WholeWord,
  WrapText,
} from 'lucide-react'

export type ToolBadge = 'client-side' | 'server-assisted'
export type ToolStatus = 'available' | 'coming-soon'

export type CategoryId =
  'markdown' | 'image' | 'files' | 'pdf-office' | 'converters' | 'text-dev' | 'security'

export interface ToolCategory {
  id: CategoryId
  name: string
  icon: LucideIcon
}

export interface ToolMeta {
  /** Route slug: `/tools/<slug>` and `src/tools/<slug>/`. */
  slug: string
  name: string
  description: string
  category: CategoryId
  badge: ToolBadge
  status: ToolStatus
  /** Phase number in PLAN.md — build order reference only. */
  phase: number
  icon: LucideIcon
}

export const categories: ToolCategory[] = [
  { id: 'markdown', name: 'Markdown', icon: FileText },
  { id: 'image', name: 'Image', icon: Image },
  { id: 'files', name: 'Files', icon: Files },
  { id: 'pdf-office', name: 'PDF & Office', icon: FileStack },
  { id: 'converters', name: 'Converters', icon: Repeat2 },
  { id: 'text-dev', name: 'Text & Developer', icon: Terminal },
  { id: 'security', name: 'Security & Inspection', icon: Shield },
]

const soon = 'coming-soon' as const
const client = 'client-side' as const

export const tools: ToolMeta[] = [
  // ── Markdown ──────────────────────────────────────────────────────────
  {
    slug: 'em-dash-remover',
    name: 'Em-dash remover',
    description: 'Replace or remove em-dashes in text',
    category: 'markdown',
    badge: client,
    status: 'available',
    phase: 1,
    icon: RemoveFormatting,
  },
  {
    slug: 'double-line-remover',
    name: 'Double line remover',
    description: 'Collapse repeated blank lines',
    category: 'markdown',
    badge: client,
    status: 'available',
    phase: 2,
    icon: WrapText,
  },
  {
    slug: 'diff-checker',
    name: 'Diff checker',
    description: 'Compare two texts side by side',
    category: 'markdown',
    badge: client,
    status: 'available',
    phase: 3,
    icon: GitCompare,
  },
  {
    slug: 'markdown-renderer',
    name: 'Markdown renderer',
    description: 'Live GFM preview with highlighting',
    category: 'markdown',
    badge: client,
    status: 'available',
    phase: 4,
    icon: Eye,
  },
  {
    slug: 'mermaid-editor',
    name: 'Mermaid editor',
    description: 'Write and render diagrams, export SVG/PNG',
    category: 'markdown',
    badge: client,
    status: 'available',
    phase: 5,
    icon: Workflow,
  },
  {
    slug: 'markdown-editor',
    name: 'Markdown editor',
    description: 'Full editor with toolbar, images, autosave',
    category: 'markdown',
    badge: client,
    status: 'available',
    phase: 6,
    icon: PenLine,
  },

  // ── Image ─────────────────────────────────────────────────────────────
  {
    slug: 'image-resize',
    name: 'Image resize',
    description: 'Resize by pixels or percent, in batch',
    category: 'image',
    badge: client,
    status: 'available',
    phase: 7,
    icon: Scaling,
  },
  {
    slug: 'background-remover',
    name: 'Background remover',
    description: 'AI background removal, fully in-browser',
    category: 'image',
    badge: client,
    status: 'available',
    phase: 8,
    icon: Eraser,
  },
  {
    slug: 'image-format-converter',
    name: 'Format converter',
    description: 'Convert PNG, JPEG, WebP and AVIF',
    category: 'image',
    badge: client,
    status: soon,
    phase: 42,
    icon: Repeat,
  },
  {
    slug: 'image-compressor',
    name: 'Image compressor',
    description: 'Shrink photos with quality preview',
    category: 'image',
    badge: client,
    status: soon,
    phase: 43,
    icon: ImageDown,
  },
  {
    slug: 'crop-rotate-flip',
    name: 'Crop / rotate / flip',
    description: 'Precise cropping with presets',
    category: 'image',
    badge: client,
    status: soon,
    phase: 44,
    icon: Crop,
  },
  {
    slug: 'exif-viewer',
    name: 'EXIF viewer & stripper',
    description: 'View and remove photo metadata and GPS',
    category: 'image',
    badge: client,
    status: soon,
    phase: 45,
    icon: Camera,
  },
  {
    slug: 'svg-optimizer',
    name: 'SVG optimizer',
    description: 'Minify SVG safely',
    category: 'image',
    badge: client,
    status: soon,
    phase: 46,
    icon: Shapes,
  },
  {
    slug: 'favicon-generator',
    name: 'Favicon generator',
    description: 'One image → full favicon set',
    category: 'image',
    badge: client,
    status: soon,
    phase: 47,
    icon: Sparkles,
  },
  {
    slug: 'color-palette-extractor',
    name: 'Color palette extractor',
    description: 'Dominant colors from any image',
    category: 'image',
    badge: client,
    status: soon,
    phase: 48,
    icon: Palette,
  },

  // ── Files ─────────────────────────────────────────────────────────────
  {
    slug: 'bulk-file-hasher',
    name: 'Bulk file hasher',
    description: 'SHA/MD5 checksums for many files',
    category: 'files',
    badge: client,
    status: 'available',
    phase: 9,
    icon: Fingerprint,
  },
  {
    slug: 'bulk-file-renamer',
    name: 'Bulk file renamer',
    description: 'Pattern-rename files, export as zip',
    category: 'files',
    badge: client,
    status: 'available',
    phase: 10,
    icon: FileSignature,
  },
  {
    slug: 'zip-unzip',
    name: 'Zip / unzip',
    description: 'Create and extract archives',
    category: 'files',
    badge: client,
    status: soon,
    phase: 49,
    icon: FolderArchive,
  },
  {
    slug: 'duplicate-file-finder',
    name: 'Duplicate file finder',
    description: 'Find identical files by content',
    category: 'files',
    badge: client,
    status: soon,
    phase: 50,
    icon: CopyCheck,
  },
  {
    slug: 'ocr',
    name: 'OCR',
    description: 'Extract text from images and scans',
    category: 'files',
    badge: client,
    status: soon,
    phase: 51,
    icon: ScanText,
  },

  // ── PDF & Office ──────────────────────────────────────────────────────
  {
    slug: 'pdf-split',
    name: 'PDF split / extract',
    description: 'Pull pages out of a PDF',
    category: 'pdf-office',
    badge: client,
    status: 'available',
    phase: 11,
    icon: Scissors,
  },
  {
    slug: 'pdf-resize',
    name: 'PDF resize',
    description: 'Change page dimensions',
    category: 'pdf-office',
    badge: client,
    status: 'available',
    phase: 12,
    icon: Expand,
  },
  {
    slug: 'pdf-to-image-markdown',
    name: 'PDF → image / markdown',
    description: 'Render pages or extract text',
    category: 'pdf-office',
    badge: client,
    status: 'available',
    phase: 13,
    icon: FileOutput,
  },
  {
    slug: 'pdf-merge',
    name: 'PDF merge',
    description: 'Combine PDFs in any order',
    category: 'pdf-office',
    badge: client,
    status: soon,
    phase: 16,
    icon: Combine,
  },
  {
    slug: 'pdf-page-organizer',
    name: 'Page reorder / rotate / delete',
    description: 'Rearrange a PDF visually',
    category: 'pdf-office',
    badge: client,
    status: soon,
    phase: 17,
    icon: ListOrdered,
  },
  {
    slug: 'pdf-watermark',
    name: 'PDF watermark',
    description: 'Stamp text or image',
    category: 'pdf-office',
    badge: client,
    status: soon,
    phase: 18,
    icon: Stamp,
  },
  {
    slug: 'images-to-pdf',
    name: 'Images → PDF',
    description: 'Photos into one document',
    category: 'pdf-office',
    badge: client,
    status: soon,
    phase: 19,
    icon: FileImage,
  },
  {
    slug: 'pdf-compress',
    name: 'PDF compress',
    description: 'Shrink heavy PDFs',
    category: 'pdf-office',
    badge: client,
    status: soon,
    phase: 20,
    icon: Shrink,
  },
  {
    slug: 'xlsx-csv-viewer',
    name: 'XLSX / CSV viewer',
    description: 'Open spreadsheets read-only',
    category: 'pdf-office',
    badge: client,
    status: soon,
    phase: 21,
    icon: Table,
  },
  {
    slug: 'pdf-editor',
    name: 'PDF editor',
    description: 'Overlay text, images, signatures and shapes',
    category: 'pdf-office',
    badge: client,
    status: soon,
    phase: 52,
    icon: PenTool,
  },

  // ── Converters ────────────────────────────────────────────────────────
  {
    slug: 'docx-to-html-markdown',
    name: 'DOCX → HTML / Markdown',
    description: 'Convert Word docs in-browser',
    category: 'converters',
    badge: client,
    status: soon,
    phase: 14,
    icon: FileCode,
  },
  {
    slug: 'docx-pdf',
    name: 'DOCX ↔ PDF',
    description: 'High-fidelity conversion via our server',
    category: 'converters',
    badge: 'server-assisted',
    status: soon,
    phase: 15,
    icon: Repeat2,
  },
  {
    slug: 'markdown-to-docx',
    name: 'Markdown → DOCX',
    description: 'Markdown to Word',
    category: 'converters',
    badge: client,
    status: soon,
    phase: 22,
    icon: FileType,
  },

  // ── Text & Developer ──────────────────────────────────────────────────
  {
    slug: 'json-formatter',
    name: 'JSON formatter',
    description: 'Format and validate JSON',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 23,
    icon: Braces,
  },
  {
    slug: 'yaml-json-toml',
    name: 'YAML ↔ JSON ↔ TOML',
    description: 'Convert config formats',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 24,
    icon: Database,
  },
  {
    slug: 'csv-json',
    name: 'CSV ↔ JSON',
    description: 'Convert tabular data',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 25,
    icon: Table2,
  },
  {
    slug: 'base64',
    name: 'Base64 encode / decode',
    description: 'Encode text and files',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 26,
    icon: Binary,
  },
  {
    slug: 'url-encode',
    name: 'URL encode / decode / parse',
    description: 'Break down URLs',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 27,
    icon: Link2,
  },
  {
    slug: 'regex-tester',
    name: 'Regex tester',
    description: 'Test patterns safely',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 28,
    icon: Regex,
  },
  {
    slug: 'case-converter',
    name: 'Case converter',
    description: 'camelCase, snake_case and friends',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 29,
    icon: CaseSensitive,
  },
  {
    slug: 'word-counter',
    name: 'Word & character counter',
    description: 'Count words, chars, tokens',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 30,
    icon: WholeWord,
  },
  {
    slug: 'uuid-password-generator',
    name: 'UUID / password generator',
    description: 'Generate secure random IDs',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 31,
    icon: KeyRound,
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp converter',
    description: 'Epoch ↔ human dates',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 32,
    icon: Clock,
  },
  {
    slug: 'cron-parser',
    name: 'Cron parser',
    description: 'Explain cron schedules',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 33,
    icon: CalendarClock,
  },
  {
    slug: 'string-escape',
    name: 'String escape / unescape',
    description: 'Escape for JSON, HTML, shell',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 34,
    icon: Quote,
  },
  {
    slug: 'dummy-data-generator',
    name: 'Dummy data generator',
    description: 'Seeded fake data',
    category: 'text-dev',
    badge: client,
    status: soon,
    phase: 35,
    icon: Sparkles,
  },

  // ── Security & Inspection ─────────────────────────────────────────────
  {
    slug: 'text-hasher',
    name: 'Text hasher + HMAC',
    description: 'Hash text, RFC-correct',
    category: 'security',
    badge: client,
    status: soon,
    phase: 36,
    icon: Hash,
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT decoder',
    description: 'Inspect tokens locally, nothing sent anywhere',
    category: 'security',
    badge: client,
    status: soon,
    phase: 37,
    icon: KeySquare,
  },
  {
    slug: 'certificate-decoder',
    name: 'Certificate decoder',
    description: 'Read X.509/CSR fields from PEM',
    category: 'security',
    badge: client,
    status: soon,
    phase: 38,
    icon: FileBadge,
  },
  {
    slug: 'hex-viewer',
    name: 'Hex viewer',
    description: "Inspect any file's raw bytes, detect real type",
    category: 'security',
    badge: client,
    status: soon,
    phase: 39,
    icon: FileDigit,
  },
  {
    slug: 'password-strength',
    name: 'Password strength checker',
    description: 'Offline zxcvbn analysis',
    category: 'security',
    badge: client,
    status: soon,
    phase: 40,
    icon: ShieldCheck,
  },
  {
    slug: 'qr-generator-reader',
    name: 'QR generator + reader',
    description: 'Create and scan QR codes',
    category: 'security',
    badge: client,
    status: soon,
    phase: 41,
    icon: QrCode,
  },
]

export function getTool(slug: string): ToolMeta | undefined {
  return tools.find((t) => t.slug === slug)
}

export function getCategory(id: CategoryId): ToolCategory {
  // Categories are a closed set; every ToolMeta.category is a CategoryId.
  return categories.find((c) => c.id === id) as ToolCategory
}

export function toolsByCategory(id: CategoryId): ToolMeta[] {
  return tools.filter((t) => t.category === id)
}
